# Generated by Django 5.2.8 on 2025-11-25 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_id', models.IntegerField()),
                ('car_brand', models.CharField(max_length=50)),
                ('car_year', models.IntegerField()),
                ('car_reg', models.IntegerField()),
                ('car_colour', models.CharField(max_length=50)),
            ],
        ),
    ]
